# 元数据信息
meta:
  name: "YukiCpuScheduler"
  author: "yuki"
  configVersion: 1
  loglevel: "INFO"

# 主要功能开关
function:
  DisableQcomGpu: false 
  AffintySetter: true
  CpuIdleScaling_Governor: false
  EasScheduler: true
  cpuset: true
  LoadBalancing: true
  EnableFeas: false
  AdjIOScheduler: true
  AppLaunchBoost: true
  EnableThreadAffinity: true

# 待机模式配置
Standby:
  Enable: false
  ScreenOffDelay: 300

# 核心分配设置 (适配天玑6080)
CoreAllocation:
  cpusetCore: "4-7"
  cpuctlUclampBoostMin: "0"
  cpuctlUclampBoostMax: "100"

# 核心框架路径 (适配天玑6080的 6小核+2大核 架构)
CoreFramework:
  SmallCorePath: 0       
  MediumCorePath: 0     
  BigCorePath: 6        
  SuperBigCorePath: 0   

# IO 调度器设置
IO_Settings:
  Scheduler: ""
  IO_optimization: true

# 其他设置
Other:
  AdjQcomBus_dcvs: false

# EAS 调度器参数
EasSchedulerValue:
  sched_min_granularity_ns: "2000000"
  sched_nr_migrate: "30"
  sched_wakeup_granularity_ns: "3200000"
  sched_schedstats: "0"

# CPU 空闲设置
CpuIdle:
  current_governor: ""

# Cpuset 分组 (适配天玑6080的 6+2 架构)
Cpuset:
  top_app: "0-7"
  foreground: "0-7"
  restricted: "0-5"             
  system_background: "0-3"     
  background: "0-5"             

# --- 性能模式  ---

# 省电模式
powersave:
  scaling_governor: "schedutil"
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "0"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "70"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 500
  SmallCoreMaxFreq: 1200    
  MediumCoreMinFreq: "min"      
  MediumCoreMaxFreq: "min"     
  BigCoreMinFreq: 600
  BigCoreMaxFreq: 1400      
  SuperBigCoreMinFreq: "min"
  SuperBigCoreMaxFreq: "min"
  ufsClkGate: false

# 均衡模式
balance:
  scaling_governor: "schedutil" 
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "0"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "70"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 600
  SmallCoreMaxFreq: 1800     
  MediumCoreMinFreq: "min"      
  MediumCoreMaxFreq: "min"      
  BigCoreMinFreq: 800
  BigCoreMaxFreq: 2000      
  SuperBigCoreMinFreq: "min"
  SuperBigCoreMaxFreq: "min"
  ufsClkGate: false

# 性能模式
performance:
  scaling_governor: "schedutil"
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "1"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "80"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 800
  SmallCoreMaxFreq: 2000      
  MediumCoreMinFreq: "min"      
  MediumCoreMaxFreq: "min"      
  BigCoreMinFreq: 1000
  BigCoreMaxFreq: 2400      
  SuperBigCoreMinFreq: "min"
  SuperBigCoreMaxFreq: "min"
  ufsClkGate: false

# 极速模式
fast:
  scaling_governor: "performance" 
  UclampTopAppMin: "10"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "1"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "80"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 1200
  SmallCoreMaxFreq: "max"
  MediumCoreMinFreq: "min"
  MediumCoreMaxFreq: "min"
  BigCoreMinFreq: 1200
  BigCoreMaxFreq: "max"
  SuperBigCoreMinFreq: "min"
  SuperBigCoreMaxFreq: "min"
  ufsClkGate: true