# 元数据信息
meta:
  name: "YukiCpuScheduler"
  author: "yuki"
  configVersion: 15
  loglevel: "INFO"

# 主要功能开关
function:
  DisableQcomGpu: false
  AffintySetter: true
  CpuIdleScaling_Governor: false
  EasScheduler: true
  cpuset: true
  LoadBalancing: true
  EnableFeas: false 
  AdjIOScheduler: true
  AppLaunchBoost: true
  EnableThreadAffinity: true

# 核心分配设置 (1+3+4架构)
CoreAllocation:
  cpusetCore: "4-7" 

# 核心框架路径 (适配天玑9000的 4小核+3大核+1超大核 架构)
CoreFramework:
  SmallCorePath: 0      
  MediumCorePath: 4     
  BigCorePath: 7         
  SuperBigCorePath: -1   

# IO 调度器设置
IO_Settings:
  Scheduler: ""
  IO_optimization: true

# 其他设置
Other:
  AdjQcomBus_dcvs: false

# EAS 调度器参数
EasSchedulerValue:
  sched_min_granularity_ns: "2000000"
  sched_nr_migrate: "30"
  sched_wakeup_granularity_ns: "3200000"
  sched_schedstats: "0"

# CPU 空闲设置
CpuIdle:
  current_governor: ""

# Cpuset 分组
Cpuset:
  top_app: "0-7"
  foreground: "0-7"
  restricted: "0-5"
  system_background: "1-2"
  background: "0-2"

# --- 性能模式 ---

# 省电模式
powersave:
  scaling_governor: "schedutil"
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "0"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "70"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 220000
  SmallCoreMaxFreq: 1300000
  MediumCoreMinFreq: 400000
  MediumCoreMaxFreq: 1700000
  BigCoreMinFreq: 1200000
  BigCoreMaxFreq: 1900000
  SuperBigCoreMinFreq: "min"
  SuperBigCoreMaxFreq: "min"
  ufsClkGate: false

# 均衡模式
balance:
  scaling_governor: "schedutil"
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "0"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "70"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 800000
  SmallCoreMaxFreq: 1800000
  MediumCoreMinFreq: 1200000
  MediumCoreMaxFreq: 2200000
  BigCoreMinFreq: 1500000
  BigCoreMaxFreq: 2500000
  SuperBigCoreMinFreq: "min" 
  SuperBigCoreMaxFreq: "min" 
  ufsClkGate: false

# 性能模式
performance:
  scaling_governor: "schedutil"
  UclampTopAppMin: "0"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "1"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "80"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 1000000
  SmallCoreMaxFreq: 2000000
  MediumCoreMinFreq: 1600000
  MediumCoreMaxFreq: 2850000
  BigCoreMinFreq: 1800000
  BigCoreMaxFreq: 3200000
  SuperBigCoreMinFreq: "min" 
  SuperBigCoreMaxFreq: "min" 
  ufsClkGate: false

# 极速模式
fast:
  scaling_governor: "schedutil" 
  UclampTopAppMin: "10"
  UclampTopAppMax: "100"
  UclampTopApplatency_sensitive: "1"
  UclampForeGroundMin: "0"
  UclampForeGroundMax: "80"
  UclampBackGroundMin: "0"
  UclampBackGroundMax: "50"
  SmallCoreMinFreq: 1200
  SmallCoreMaxFreq: "max"
  MediumCoreMinFreq: 1600
  MediumCoreMaxFreq: "max"
  BigCoreMinFreq: 1800
  BigCoreMaxFreq: "max"
  SuperBigCoreMinFreq: "min" 
  SuperBigCoreMaxFreq: "min" 
  ufsClkGate: true