# 元数据信息
meta:
  name: "YukiCpuScheduler"
  author: "yuki"
  configVersion: 16
  loglevel: "INFO"

# 主要功能开关
function:
  DisableQcomGpu: true
  AffintySetter: true
  CpuIdleScaling_Governor: false
  EasScheduler: true
  cpuset: true
  LoadBalancing: true
  EnableFeas: false
  AdjIOScheduler: true
  AppLaunchBoost: false
  EnableThreadAffinity: true

# 待机模式配置
Standby:
  Enable: false
  ScreenOffDelay: 300

# 核心分配设置
CoreAllocation:
  cpusetCore: "4-7"
  cpuctlUclampBoostMin: "0"
  cpuctlUclampBoostMax: "100"

# 核心框架路径
CoreFramework:
  SmallCorePath: 0
  MediumCorePath: 4
  BigCorePath: 7
  SuperBigCorePath: -1

# IO 调度器设置
IO_Settings:
  Scheduler: ""
  IO_optimization: true

# 其他设置
Other:
  AdjQcomBus_dcvs: false

# EAS 调度器参数
EasSchedulerValue:
  sched_min_granularity_ns: "2000000"
  sched_nr_migrate: "30"
  sched_wakeup_granularity_ns: "3200000"
  sched_schedstats: "0"

# CPU 空闲设置
CpuIdle:
  current_governor: ""

# Cpuset 分组
Cpuset:
  top_app: "0-7"
  foreground: "0-7"
  restricted: "0-5"
  system_background: "1-2"
  background: "0-2"

# --- 性能模式 ---

# 省电模式
powersave:
  # 调速器
  Governor:
    global: "schedutil"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 600000
    SmallCoreMaxFreq: 1300000
    MediumCoreMinFreq: 800000
    MediumCoreMaxFreq: 1400000
    BigCoreMinFreq: 800000
    BigCoreMaxFreq: 1500000
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0 
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "0"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "70"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  # 其他设置
  Other:
    ufsClkGate: false

# 均衡模式
balance:
  # 调速器
  Governor:
    global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 600000
    SmallCoreMaxFreq: 1620000
    MediumCoreMinFreq: 700000
    MediumCoreMaxFreq: 1725000
    BigCoreMinFreq: 800000
    BigCoreMaxFreq: 2000000
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0 
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "0"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "70"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  # 其他设置
  Other:
    ufsClkGate: false

# 性能模式
performance:
  # 调速器
  Governor:
    global: "schedutil"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 1000000
    SmallCoreMaxFreq: "max"
    MediumCoreMinFreq: 900000
    MediumCoreMaxFreq: 2250000
    BigCoreMinFreq: 1000000
    BigCoreMaxFreq: 2610000
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0 
  # 频率限制
  Uclamp:
    UclampTopAppMin: "0"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "80"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  # 其他设置
  Other:
    ufsClkGate: false

# 极速模式
fast:
  # 调速器
  Governor:
    global: "walt"
    SmallCore: ""
    MediumCore: ""
    BigCore: ""
    SuperBigCore: ""
  # 频率
  Freq:
    SmallCoreMinFreq: 1000000
    SmallCoreMaxFreq: "max"
    MediumCoreMinFreq: 900000
    MediumCoreMaxFreq: "max"
    BigCoreMinFreq: 1000000
    BigCoreMaxFreq: "max"
    SuperBigCoreMinFreq: 0
    SuperBigCoreMaxFreq: 0
  # 频率限制
  Uclamp:
    UclampTopAppMin: "10"
    UclampTopAppMax: "100"
    UclampTopApplatency_sensitive: "1"
    UclampForeGroundMin: "0"
    UclampForeGroundMax: "80"
    UclampBackGroundMin: "0"
    UclampBackGroundMax: "50"
  # 其他设置
  Other:
    ufsClkGate: true